name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      id: install
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl shellcheck
      if: success()

    - name: Shell script syntax check
      id: lint
      run: |
        shellcheck generate-ssl-cert.sh
        shellcheck install-proxmox-cert.sh
        shellcheck tests/run-tests.sh
      if: steps.install.outcome == 'success'

    - name: Run test suite
      id: test_suite
      run: |
        cd tests
        ./run-tests.sh
        echo "TEST_LOG<<EOF" >> $GITHUB_ENV
        cat test_results.log >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      if: steps.lint.outcome == 'success'

    - name: Security scan
      id: security
      uses: github/codeql-action/init@v2
      with:
        languages: shell
      if: steps.test_suite.outcome == 'success'

    - name: Run CodeQL Analysis
      id: codeql
      uses: github/codeql-action/analyze@v2
      if: steps.security.outcome == 'success'

    - name: Prepare test report
      id: report
      if: always()
      run: |
        {
          echo "SSL Certificate Generator Test Report"
          echo "==================================="
          echo
          echo "Build Status:"
          echo "-------------"
          echo "Dependencies Installation: ${{ steps.install.outcome }}"
          echo "Shellcheck Linting: ${{ steps.lint.outcome }}"
          echo "Test Suite: ${{ steps.test_suite.outcome }}"
          echo "Security Scan: ${{ steps.security.outcome }}"
          echo "CodeQL Analysis: ${{ steps.codeql.outcome }}"
          echo
          echo "Detailed Test Results:"
          echo "--------------------"
          echo "${{ env.TEST_LOG }}"
        } > test_report.txt

    - name: Send email on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.SMTP_SERVER}}
        server_port: ${{secrets.SMTP_PORT}}
        username: ${{secrets.SMTP_USERNAME}}
        password: ${{secrets.SMTP_PASSWORD}}
        subject: "⚠️ SSL Certificate Generator: Tests Failed"
        body: |
          SSL Certificate Generator tests have failed!
          
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          
          Failed Step: ${{ steps.install.outcome == 'failure' && 'Dependencies' || steps.lint.outcome == 'failure' && 'Linting' || steps.test_suite.outcome == 'failure' && 'Test Suite' || steps.security.outcome == 'failure' && 'Security Scan' || steps.codeql.outcome == 'failure' && 'CodeQL Analysis' || 'Unknown' }}
          
          Test Report:
          $(cat test_report.txt)
          
          View detailed logs:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{secrets.NOTIFICATION_EMAIL}}
        from: SSL Certificate Generator CI <${{secrets.SMTP_USERNAME}}>
        attachments: ./test_report.txt

    - name: Send success notification
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.SMTP_SERVER}}
        server_port: ${{secrets.SMTP_PORT}}
        username: ${{secrets.SMTP_USERNAME}}
        password: ${{secrets.SMTP_PASSWORD}}
        subject: "✅ SSL Certificate Generator: All Tests Passed"
        body: |
          SSL Certificate Generator tests completed successfully!
          
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          
          Test Report:
          $(cat test_report.txt)
          
          All tests passed successfully. No action required.
          
          View detailed logs:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{secrets.NOTIFICATION_EMAIL}}
        from: SSL Certificate Generator CI <${{secrets.SMTP_USERNAME}}>
        attachments: ./test_report.txt

